# -*- coding: utf-8 -*-
"""Exercício 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aalkizmIfnSOhiZbmnM1fshANs0q7zJq

Crie um vetor com 5 elementos inteiros.
"""

vetorteste = [1,2,3,4,5]
print (vetorteste)

""" Calcule a soma de todos os elementos do vetor.

"""

Soma= sum(vetorteste)
print ("A soma é igual a",Soma)

"""Verifique se todos os elementos do vetor são positivos e imprima o resultado (se é
positivo ou não)

"""

if (vetorteste[0]>=1) & (vetorteste[1]>=1) & (vetorteste[2]>=1) & (vetorteste[3]>=1) & (vetorteste[4]>=1):
  print("sim, todos os elementos são positivos")
else:
  print("não, nem todos os elementos são negativo")

"""Calcule a média aritmética dos elementos do vetor, utilize as funções vistas em aula
gravada
"""

QuantidadeElementos = len(vetorteste)
Media = Soma / QuantidadeElementos
print ("A média é igual a",Media)

"""Remova o item da posição 4 e calcule novamente a média

"""

vetorteste[4] = 0
Soma2 = sum(vetorteste)
Media2 = Soma2 / QuantidadeElementos
print (" A Média é igual a" ,Media2)

""" Escreva uma função que receba duas strings e verifique se são iguais.

"""

def compare(x , y):
  if (x == y):
    print ("As strings são iguais")
  else:
    print ("As strings são diferentes")

nome1 = "Matheus"
nome2 = "Mateus"
nome3 = "Matheus"

compare(nome1, nome2)
compare(nome1, nome3)

"""7 - Escreva uma função que receba uma lista de números e retorne a média deles.

"""

def Medialista(vetor):
  QuantidadeElementos = len(vetor)
  Soma = sum(vetor)
  Media = Soma / QuantidadeElementos
  print ("A média é igual a",Media)

vetorteste1 = [1,3,5,7,11]
vetorteste2 = [2,4,6,8,10]

Medialista (vetorteste1)
Medialista (vetorteste2)

"""8 - Escreva uma função que, dado o valor da conta de um restaurante, calcule e exiba a
gorjeta do garçom, considerando 10% do valor da conta.

"""

def conta(valor):
    total = (valor * 0.1) + valor
    print ("O total é" ,total)

valorcomanda = 100
conta(valorcomanda)

"""9 - Crie uma função que receba o tempo em segundos e informe quantas horas tem nele.

"""

def convSecToHour(segundos):
  horas = segundos / 3600
  print ("Em" ,segundos, "segundos tem" ,horas, "hora(s).")

convSecToHour(3600)

"""10 - Crie uma função que receba um número e retorne seu sucessor e antecessor."""

def suceEant(numero):
  suce = numero + 1
  ant = numero - 1
  print ("O sucessor de" ,numero, "é" ,suce, "e o antecessor é" ,ant,".")

suceEant(5)